#!/usr/bin/env python3
import argparse
import os
import re
import sys

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.description = 'Filename extension manipulation tool'

    subparsers = parser.add_subparsers()

    add_parser = subparsers.add_parser('add', help='Add extension')
    add_parser.set_defaults(command='add')
    add_parser.add_argument('extension', action='store')
    add_parser.add_argument('file', action='store')

    rm_parser = subparsers.add_parser('rm', help='Remove extension')
    rm_parser.set_defaults(command='rm')
    rm_parser.add_argument('file', action='store')

    # HACK: Print usage and error message
    if len(sys.argv) == 1:
        parser.print_help()
        quit()
    args = parser.parse_args()

    file = args.file
    if args.command == 'add':
        extension = args.extension
        os.system(f'mv {file} {file}.{extension}')
    else:
        os.system(f'mv {file} {os.path.splitext(file)[0]}')
